apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-machineset
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-appsets
    repoURL: https://github.com/francisholtIBM/testing
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true